name: release

on:
  push:
    tags:
      - '*'

jobs:
  package-cimbar:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

  package-cimbar-windows:
    runs-on: windows-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: '5568f110b509a9fd90711978a7cb76bae75bb092'

      - name: Install OpenCV and GLFW with vcpkg
        run: |
          vcpkg install opencv:x64-windows glfw3:x64-windows

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"

      - name: Build
        run: |
          cd build
          cmake --build . --config Release

      - name: Install
        run: |
          cd build
          cmake --install . --config Release

      - name: Upload Windows build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cimbar-windows
          path: dist/bin/cimbar.exe

      - name: Create ZIP archive
        run: |
          Compress-Archive -Path dist/bin/cimbar.exe -DestinationPath cimbar-windows.zip

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: cimbar-windows.zip

      - name: Get openCV
        run: |
          git clone --recurse-submodules --depth 1 --branch 4.11.0 https://github.com/opencv/opencv.git opencv4

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: emscripten/emsdk:3.1.69
          options: -v ${{ github.workspace }}:/usr/src/app
          shell: bash
          run: |
            bash /usr/src/app/package-wasm.sh

      - name: Show results
        run: ls -l web/

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            web/cimbar.asmjs.zip
            web/cimbar.wasm.tar.gz
            web/cimbar_js.html

